from flask import Blueprint
app = Blueprint("Main", __name__)
from api.login import *
from api.shops import *
from api.proifle import *
from api.bind_withdrawal import *
from api.transactions import *
from api.trade import *
from api.withdrawal import *
from api.deposits import *
from api.admin import *